### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by DSchau** [NebraskaJS/speaker-signup#2]
Specifically how we can utilize/call GraphQL endpoints with some of the client-side libraries, e.g. Apollo!

(not opposed to speaking on this, doing some research, but would have to be a few months out!)

**Comment by JDegner0129** [comment]
:wave: I've never been to NebraskaJS but I'd also be potentially interested in this topic :smile: -- I'd be glad to do the presentation I gave at [AIM HDC](http://sched.co/B9D1) earlier this year, but that one's focused more on features of the query language than integration with frontend using something like Apollo Client or Relay.

I could tweak that presentation to focus more on frontend but I'd be in the same boat as @DSchau -- it'd probably be a couple months until I have something together!

**Comment by DSchau** [comment]
@JDegner0129 in general, I think _something_ on GraphQL is more valuable than not, so would definitely still be interested with a presentation on the features of GraphQL. I think others would find that interesting, as well.

So yeah, definitely something to consider!

**Comment by nicknisi** [comment]
@DSchau @JDegner0129 This would be a great topic! I'm assuming that neither of you would have anything for the February meetup? If not, would either of you like to speak about this in April?

**Comment by DSchau** [comment]
@nicknisi I'm in for April unless @JDegner0129 wants to snag it before me in February!

**Comment by JDegner0129** [comment]
@DSchau it's all you! Depending on what the specifics of the talk are, I might be able to do a follow-up or something like that. 😄

**Comment by nicknisi** [comment]
@DSchau Just checking in to see if you're still interested in presenting on GraphQL on April 3rd?

**Comment by DSchau** [comment]
@nicknisi I was actually going to post this morning I'm still interested :)

Definitely still in and I'll have something to demo/present by then for sure.

**Comment by nicknisi** [comment]
Excellent! Thank you! I'll get the meetup scheduled promptly after our March Meetup.

**Comment by DSchau** [comment]
@nicknisi would we be able to push this out to more mid-late April, or does the 3rd work the best?

Some more time to create some useful, real-world demos would be helpful!

**Comment by nicknisi** [comment]
@DSchau hmm... how about we move this talk to our May 1st meetup?

**Comment by DSchau** [comment]
That works for me! Sorry for the delay!!

**Comment by DSchau** [comment]
Closing with the [presentation](https://graphql.dustinschau.com) I just gave. Not ruling out others giving a talk about GraphQL however :)

And the [meetup](https://www.meetup.com/nebraskajs/events/dxndfdyxhbcb/)
