### ISSUE TITLE
GopherJS & Vecty

### ISSUE THREAD

**Issue by jmhobbs** [NebraskaJS/speaker-signup#3]
I would be willing to share what I know about the slightly horrifying GopherJS & Vecty world at some point.

**Comment by nicknisi** [comment]
@Jmhobbs is this something you’d be interested in/willing to present at the February Meetup?

**Comment by nicknisi** [comment]
Tentatively scheduling for March 2018

**Comment by nicknisi** [comment]
Thanks, John!
