### ISSUE TITLE
Web Components with Stencil

### ISSUE THREAD

**Issue by TheBrockEllis** [NebraskaJS/speaker-signup#4]
Web components are a huge part of the future of the web. I've got bunches of experience with the Ionic framework which uses Stencil under the hood to generate components in the latest version, but don't know much about Stencil itself. I would be willing to dive in and learn in order to give a talk about it if folks would be interested. Or if someone already has some experience, I'd love to listen!

**Comment by mattdsteele** [comment]
@cary-smith and I are eyeing Stencil (and WCs more generally)

Also /cc @splitinfinities

**Comment by DSchau** [comment]
@TheBrockEllis @mattdsteele awesome! Yes, have definitely been wanting to check out Stencil, seems like a really great library.

**Comment by cary-smith** [comment]
So far I see nothing but good things in it. Speedy too.

**Comment by splitinfinities** [comment]
I would love to give a talk on web components, with or without shadow dom. It's been a large motivation of mine to learn the pattern throughout 2017. Let me know if you ever have a free spot!

**Comment by nicknisi** [comment]
@TheBrockEllis @splitinfinities @mattdsteele Any chance one of you could present on this at the February meetup on 2/6?

**Comment by nicknisi** [comment]
Thanks, Will! I'll be posting the video soon!
