### ISSUE TITLE
Understanding the WebSocket Protocol

### ISSUE THREAD

**Issue by benstevinson** [NebraskaJS/speaker-signup#5]
I'm a really big fan of WebSockets -- they're a lightweight bi-directional communications channel that doesn't have a lot of overhead.

I've been working on a talk about the protocol itself -- more how the actual communication between the browser and the server happens, from handshake to close, and less on how to implement them/use them in practice.

Might be interesting!

**Comment by nicknisi** [comment]
@benstevinson This would be a great topic! Is this something you'd still be interested in speaking about at an upcoming NebraskaJS meetup?

**Comment by benstevinson** [comment]
@nicknisi Absolutely! I actually have the talk put together (I gave it at a ruby meetup a long while back), so I'm able to give it whenever. I still think it's a really great topic!

**Comment by nicknisi** [comment]
Agreed! I was at that ruby meetup! Would September 4th be too soon? How long would you speak for?

**Comment by benstevinson** [comment]
@nicknisi Oh yeah, you gave an awesome Typescript talk that day too!

September 4th works great for me, I'd love to. I'd expect my talk to be around 35-45 minutes.

**Comment by nicknisi** [comment]
Perfect! Thanks so much! I'll double check that the room is available and then get the meetup created. Would you happen to have a title and synopsis that you'd like on the meetup page?

**Comment by benstevinson** [comment]
Yeah, let's do:
Title: Touring the WebSocket Protocol
Synopsis: WebSockets are a fantastic tool for providing realtime
interaction within your web applications. We're going to examine how they
work under the hood and discuss what's actually involved in establishing a
connection and shipping data back and forth from client to server.

That sound good?
