### ISSUE TITLE
TypeScript 

### ISSUE THREAD

**Issue by Ne0nx3r0** [NebraskaJS/speaker-signup#8]
Not sure if there's interest in it but I've done a fair amount of work with TypeScript and I'd feel confident giving a talk on it.

Go over what it is and the benefits, how strong types in JS work, enums, generics, type guards, typing files, the typescript watcher and how it feeds into the transpilation workflow.

**Comment by DSchau** [comment]
Yeah definitely! I love TypeScript, and use it a fair amount with both NodeJS and frontend projects (e.g. React), so I'd love to see more stuff in this space, particularly just to see how others are leveraging the fair amount of features TypeScript offers.

I know @mattdsteele gave a talk--although I believe it was at OJUG--that was basically an introduction to TypeScript for Java developers, but I think any type of TypeScript content would be valuable.

**Comment by mattdsteele** [comment]
@Ne0nx3r0 Do it!
